### ISSUE TITLE
Have the ability to use a reference to secrets for the backend environment variables.

### ISSUE THREAD

**Issue by bmassemin** [suitenumerique/meet#555]
## Feature Request

With Helm deployment, environment variables must be written in plain text in the `values.yml`. However, with a GitOps approach, the `values.yml` must be committed to Git.

 It would be beneficial to use a secret to map the environment variables to the backend.

Here is the link to the documentation: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables

**Comment by rouja** [comment]
Hi,

You already can do it like this : 

```
backend:
  envVars:
    DJANGO_SUPERUSER_PASSWORD:
      secretKeyRef:
        name: backend
        key: DJANGO_SUPERUSER_PASSWORD
```
